---
#send server deploy request

#required vars
#server_name
#description
#image_id
#server_password
#private_ip

- hosts: localhost
  vars:
    cloudapiurl: api-au.dimensiondata.com
    orgid: e2c43389-90de-4498-b7d0-056e8db0b381
    user: dev1-yasuhiro.yao
    password: Zettai23
  tasks:
  - name: deploy a server
    action: uri url=https://{{ cloudapiurl }}/oec/0.9/{{ orgid }}/deployServer HEADER_Content-type="application/xml" method=POST force_basic_auth=yes user={{ user }} password={{ password }} body="<DeployServer xmlns=\"http://oec.api.opsource.net/schemas/server\"><name>{{ server_name }}</name><description>{{ description }}</description><imageId>{{ image_id }}</imageId><start>true</start><administratorPassword>{{ server_password }}</administratorPassword><privateIp>{{ private_ip }}</privateIp><disk scsiId=\"0\" speed=\"ECONOMY\"/></DeployServer>"


