---
- name: Create network
  uri:
   url: https://{{ api_url }}/caas/2.0/{{ org_id }}/network/deployVlan
   method: POST
   user: "{{ username }}"
   password: "{{ password }}"
   HEADER_Content-Type: "application/xml"
   body: "<deployVlan xmlns=\"urn:didata.com:api:cloud:types\"><networkDomainId>{{ network_domain_id }}</networkDomainId><name>{{ network_name }}</name><privateIpv4BaseAddress>{{ private_ipv4 }}</privateIpv4BaseAddress><privateIpv4PrefixSize>{{ prefix_size }}</privateIpv4PrefixSize></deployVlan>"