- hosts: localhost
  vars:
    name: Apache
    description: Apache Server
    imageid: 2247ac70-ec24-42fc-af0d-0e423199c0b9
	server_password: P@ssw0rd123
	private_ip: 10.0.71.51
  tasks:
  - name: copy template and replace variable
    file: path=./temp.xml state=absent
    copy: src=./request.xml dest=./temp.xml owner=jenkins group=jenkins mode=0755
	replace: >-
	  dest='./temp.xml'
	  regexp='{{ item.regexp }}'
	  replace='{{ item.replace }}'
	with_items:
	- regexp: 'SERVERNAME'
	  replace: {{ name }}
	- regexp: 'DESCRIPTION'
	  replace: {{ description }}
	- regexp: 'SOURCEIMAGEID'
	  replace: {{  imageid  }}
	- regexp: 'VMPASSWORD'
	  replace: {{ server_password }}
	- regexp: 'PRIVATEIP'
	  replace: {{ private_ip }}
