---
- hosts: localhost
  vars:
    cloudapiurl: api-au.dimensiondata.com
    orgid: e2c43389-90de-4498-b7d0-056e8db0b381
    user: dev1-yasuhiro.yao
    password: Zettai23
    name: Apache
    description: Apache Server
    imageid: 2247ac70-ec24-42fc-af0d-0e423199c0b9
  tasks:
  - name: deploy a server
    get_url: url=https://{{ cloudapiurl }}/oec/0.9/{{ orgid }}/deployServer dest=./deployresult url_username={{ user }} url_password={{ password }}
